apiVersion: v1
kind: Service
metadata:
  name: video-call-service
  namespace: knu-chat-namespace
spec:
  selector:
    app: video-call
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
